/samplespring:
  application:
    name: nxtims-web
  boot:
    admin:
      auto-deregistration: true
      client:
        prefer-ip: true
mail:
  host: 203.228.216.25
  default-encoding: UTF-8
  system-name: LET'S
  homepage-url: http://gaia.e-hlc.com
  from-email: nxtims@e-hlc.com
  from-name: TEAMS
  subject-prefix: TEAMS
ftp:
  server: 203.228.216.29
  username: global
  password: global15
  mode: P
---
spring:
  profiles: default
server:
  port: 7310
system:
  api:
    server:
      url: http://10.41.104.189:7311/
  temp-local-dir: C:\\temp\\    
---
spring:
  profiles: development
  boot:
    admin:
      url: http://app-hlcadmin-dev.default
server:
  tomcat:
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
system:
  api:
    server:
      url: http://system-kong-dev.default
  temp-local-dir: /NOT-YET    
---
spring:
  profiles: staging
  boot:
    admin:
      url: http://app-hlcadmin-stage.default
server:
  tomcat:
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
system:
  api:
    server:
      url: http://system-kong-stage.default
  temp-local-dir: /NOT-YET  
---
spring:
  profiles: production
  boot:
    admin:
      url: http://app-hlcadmin.default
server:
  tomcat:
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
system:
  api:
    server:
      url: http://system-kong.default
  temp-local-dir: /NOT-YET    
